language: python
matrix:
  include:
    - os: linux
      sudo: true
      dist: xenial
      env: PYTHON=3.5
    - os: osx
      env: PYTHON=3.5
script:
  - "./setup.py test"
  - pip uninstall -y greenstack && ./setup.py develop && python -c "import v8py"
  - "./setup.py sdist bdist_wheel"
dist: trusty
sudo: false
group: beta
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi
install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew install python@3
    fi
  - pip install twine pytest greenstack
cache:
  directories:
  - v8
after_success:
  - curl -k --ftp-ssl --ftp-pasv -T dist/*.whl --user desertkun:${FTPS_PASSWORD}
    ftp://ftp.keycdn.com/anthillplatform/python/v8py/
env:
  global:
     secure: BhHmx/9DG85KW14O6gZC0NWh3Q9quV0gSVP5UsgC97bb/79yrihDOnuGYtOCIXLs9OsfXjipIkvVaV5VuPzdesEMKJiMeJW1mQdjgPR9fCifZllTWAiIcX/3FMRU4Va0Mg/QO2f8mVLhxOZMyXIdpj+trO8g2rGdX2JQtLLPBSexCbQyEiw6QKZTwqOieEbsdsKqCVxP6m8PbYeO8A0E3rm3LBQk6AvVy/QKdQaeTC6yRKVzeetF70GhVq3K3yTwZc6JWESdlpWjUU9mMBw5Ae2o7UJBNzSHJZ1f74Quj1718RUI+fcWz/IiUS4PFjmcvvuNiYFhk+PW3zrRuoG0+OJEzZD9Z5jOY94rY8MFu8wFDH58a1tQn2rgNnerGiCHXmGv6wcqjgLmkla/S5TsEEb9TNWiiomjDuBssJ8rUcHB4lh2BV1P0H7kiOmKH4Wgf8hfRjIrRJ/w0E6Xls2Bxu5NxJ9FXTAXJp7oRUr2/g3tAWccqyDPg9trMFM29CZuNJyUIZGHO2VaK5M6y9TjQQvdHtfGLnpXyBESki2n2qy382JnnIzaMCOdo5CJsVLwuiYaYRbIgJK+/D2tlr5KrTKuF08CAVmc0bB+xdmD57PD9a+O0AvBTRdgqyy793+9l91R1IX8nbIVn/LqZlzLPnQShHXzm1NXrBYZ69eoigQ=
